modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="ars_fauna"
version="1.0.0"
displayName="Ars Fauna"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Lyrellion, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.ars_fauna]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.ars_fauna]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration